{{- if .Values.infisical.enabled }}
apiVersion: secrets.infisical.com/v1alpha1
kind: InfisicalSecret
metadata:
  name: {{ include "config-gen.fullname" . }}-infisical
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-gen.labels" . | nindent 4 }}
spec:
  hostAPI: {{ .Values.infisical.address }}
  resyncInterval: 60

  authentication:
    universalAuth:
      credentialsRef:
        secretName: {{ .Values.infisical.authentication.universalAuth.credentialsRef.secretName }}
        secretNamespace: {{ .Values.infisical.authentication.universalAuth.credentialsRef.secretNamespace }}
      secretsScope:
        projectSlug: {{ .Values.infisical.authentication.universalAuth.secretsScope.projectSlug | quote }}
        envSlug: {{ .Values.infisical.authentication.universalAuth.secretsScope.envSlug | quote }}
        secretsPath: {{ .Values.infisical.authentication.universalAuth.secretsScope.secretsPath | quote }}
        recursive: {{ .Values.infisical.authentication.universalAuth.secretsScope.recursive }}

  managedSecretReference:
    secretName: {{ .Values.infisical.managedSecretName }}
    secretNamespace: {{ .Release.Namespace }}
    creationPolicy: Owner
{{- end }}
