apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "config-gen.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-gen.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  selector:
    matchLabels:
      {{- include "config-gen.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
