apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "config-gen.backend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-gen.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  minAvailable: {{ .Values.backend.pdb.minAvailable }}
  selector:
    matchLabels:
      {{- include "config-gen.backend.selectorLabels" . | nindent 6 }}
