apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "config-gen.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-gen.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "config-gen.frontend.fullname" . }}
  minReplicas: {{ .Values.frontend.hpa.minReplicas }}
  maxReplicas: {{ .Values.frontend.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.frontend.hpa.targetCPUUtilizationPercentage }}
