apiVersion: v1
kind: Service
metadata:
  name: {{ include "config-gen.frontend.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "config-gen.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    {{- include "config-gen.frontend.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
    - name: metrics
      port: 9113
      targetPort: metrics
      protocol: TCP
